"""Render the threat model to Markdown (+ a Mermaid DFD) and to a metrics dict.

`pytm` is supported as an OPTIONAL enhancement (imported lazily). When it is not
installed, the stdlib renderer below produces the same docs/threat-model.md, so the
default `make detect` path never depends on pytm.
"""

from __future__ import annotations

from .model import STRIDE, System
from .threats import Threat, summarize


def mermaid_dfd(system: System) -> str:
    """Build a Mermaid flowchart of the data-flow diagram with trust-boundary subgraphs."""
    shape = {"actor": ('([', '])'), "process": ('((', '))'), "datastore": ('[(', ')]')}
    nid = {e.name: f"N{i}" for i, e in enumerate(system.elements)}

    lines = ["flowchart LR"]
    # group elements by the boundary they sit behind (heuristic for a readable diagram)
    internet = ["Client App"]
    mesh = ["API Gateway", "MLOps Operator"]
    data_tier = ["Inference Service", "Model Registry", "Feature Store", "Prediction Log"]
    groups = [
        ("Internet / DMZ (untrusted)", internet),
        ("Service Mesh (authenticated)", mesh),
        ("Data Tier (confidential)", data_tier),
    ]
    for title, members in groups:
        sub = title.replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
        lines.append(f"  subgraph {sub}[\"{title}\"]")
        for e in system.elements:
            if e.name in members:
                lo, hi = shape[e.kind]
                lines.append(f"    {nid[e.name]}{lo}\"{e.name}\"{hi}")
        lines.append("  end")
    for f in system.flows:
        label = f.data + (" 🔒" if f.encrypted else "")
        lines.append(f"  {nid[f.source]} -->|{label}| {nid[f.sink]}")
    return "\n".join(lines)


def render_markdown(system: System, threats: list[Threat], generator: str) -> str:
    """Produce the full docs/threat-model.md content."""
    counts = summarize(threats)
    total = len(threats)
    out: list[str] = []
    out.append(f"# STRIDE Threat Model — {system.name}")
    out.append("")
    out.append(f"_Generated by `{generator}` · {total} threats across 6 STRIDE categories._")
    out.append("")
    out.append("> Authorized-use-only. Models are self-trained, data is synthetic. "
               "See [../../../ETHICS.md](../../../ETHICS.md).")
    out.append("")

    out.append("## Data-flow diagram")
    out.append("")
    out.append("```mermaid")
    out.append(mermaid_dfd(system))
    out.append("```")
    out.append("")

    out.append("## Trust boundaries")
    out.append("")
    out.append("| Boundary | Description |")
    out.append("| --- | --- |")
    for b in system.boundaries:
        out.append(f"| {b.name} | {b.description} |")
    out.append("")

    out.append("## STRIDE summary")
    out.append("")
    out.append("| Category | Property violated | Threats |")
    out.append("| --- | --- | --- |")
    for cat, prop in STRIDE.items():
        out.append(f"| {cat} | {prop} | {counts[cat]} |")
    out.append(f"| **Total** | | **{total}** |")
    out.append("")

    out.append("## Threats")
    out.append("")
    for cat in STRIDE:
        cat_threats = [t for t in threats if t.category == cat]
        if not cat_threats:
            continue
        out.append(f"### {cat} ({STRIDE[cat]}) — {len(cat_threats)}")
        out.append("")
        out.append("| ID | Target | Threat | Severity | Mitigation |")
        out.append("| --- | --- | --- | --- | --- |")
        for t in cat_threats:
            out.append(f"| {t.id} | {t.target} | {t.title} | {t.severity} | {t.mitigation} |")
        out.append("")
    return "\n".join(out) + "\n"


def try_pytm_model(system: System):
    """Optional path: build an equivalent pytm TM object if pytm is installed.

    Returns the pytm.TM instance, or None if pytm is unavailable. Importing is lazy
    and wrapped so the module imports cleanly without pytm.
    """
    try:
        from pytm import (  # noqa: WPS433
            TM,
            Actor,
            Boundary,
            Dataflow,
            Datastore,
            Process,
            Server,
        )
    except Exception:
        return None

    tm = TM(system.name)
    tm.description = "ML inference service threat model (pytm enhanced path)."

    bnames = {b.name: Boundary(b.name) for b in system.boundaries}
    objs: dict[str, object] = {}
    for e in system.elements:
        if e.kind == "actor":
            objs[e.name] = Actor(e.name)
        elif e.kind == "datastore":
            objs[e.name] = Datastore(e.name)
        elif e.name == "API Gateway":
            objs[e.name] = Server(e.name)
        else:
            objs[e.name] = Process(e.name)

    for f in system.flows:
        df = Dataflow(objs[f.source], objs[f.sink], f.data)
        df.protocol = f.protocol
        df.isEncrypted = f.encrypted
        if f.crosses_boundary in bnames:
            df.boundary = bnames[f.crosses_boundary]
    return tm
